# Site settings
title: Androoid Project
email: androoid.project@gmail.com
description: Androoid is an Spring Roo Add-On Suite that provides all functionalities to generate Android projects using Spring Roo shell.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://androoid.github.io" # the base hostname & protocol for your site
twitter_username: androoid.project
github_username:  androoid

# Build settings
markdown: kramdown
